### ISSUE TITLE
unrecognized option: P

### ISSUE THREAD

**Issue by nicolapippa** [italia/spid-compliant-certificates#15]
Buongiorno,
dopo l'ultimo aggironamento, quando tento di generare il certificato compaiono i seguenti errori. Come posso risolvere?

Grazie

`grep: unrecognized option: P
BusyBox v1.32.1 () multi-call binary.

Usage: grep [-HhnlLoqvsrRiwFE] [-m N] [-A/B/C N] PATTERN/-e PATTERN.../-f FILE [FILE]...

Search for PATTERN in FILEs (or stdin)

        -H      Add 'filename:' prefix
        -h      Do not add 'filename:' prefix
        -n      Add 'line_no:' prefix
        -l      Show only names of files that match
        -L      Show only names of files that don't match
        -c      Show only count of matching lines
        -o      Show only the matching part of line
        -q      Quiet. Return 0 if PATTERN is found, 1 otherwise
        -v      Select non-matching lines
        -s      Suppress open and read errors
        -r      Recurse
        -R      Recurse and dereference symlinks
        -i      Ignore case
        -w      Match whole words only
        -x      Match whole lines only
        -F      PATTERN is a literal (not regexp)
        -E      PATTERN is an extended regexp
        -m N    Match up to N times per file
        -A N    Print N lines of trailing context
        -B N    Print N lines of leading context
        -C N    Same as '-A N -B N'
        -e PTRN Pattern to match
        -f FILE Read pattern from file
sh: 1: unknown operand
grep: unrecognized option: P
BusyBox v1.32.1 () multi-call binary.

Usage: grep [-HhnlLoqvsrRiwFE] [-m N] [-A/B/C N] PATTERN/-e PATTERN.../-f FILE [FILE]...

Search for PATTERN in FILEs (or stdin)

        -H      Add 'filename:' prefix
        -h      Do not add 'filename:' prefix
        -n      Add 'line_no:' prefix
        -l      Show only names of files that match
        -L      Show only names of files that don't match
        -c      Show only count of matching lines
        -o      Show only the matching part of line
        -q      Quiet. Return 0 if PATTERN is found, 1 otherwise
        -v      Select non-matching lines
        -s      Suppress open and read errors
        -r      Recurse
        -R      Recurse and dereference symlinks
        -i      Ignore case
        -w      Match whole words only
        -x      Match whole lines only
        -F      PATTERN is a literal (not regexp)
        -E      PATTERN is an extended regexp
        -m N    Match up to N times per file
        -A N    Print N lines of trailing context
        -B N    Print N lines of leading context
        -C N    Same as '-A N -B N'
        -e PTRN Pattern to match
        -f FILE Read pattern from file
sh: 1: unknown operand
sh: PROVINCIA: unknown operand
/usr/local/bin/gencert-public: line 46: curl: not found
[E] ORGANIZATION_IDENTIFIER refers to something that does not exists
[I] Check it by yourself at https://indicepa.gov.it/ricerca/n-dettaglioamministrazione.php?cod_amm=cpiabn`

**Comment by psmiraglia** [comment]
The bug is well known and its fix should be available in [issue/13] branch (the pull request #14 is currently under review). In the meantime, could you try the [issue/13] code and provide us with a feedback?

[issue/13]: https://github.com/italia/spid-compliant-certificates/tree/issue/13

**Comment by nicolapippa** [comment]
I tried to use that version, the error is as follows.
`/usr/local/bin/gencert-public: 22: [: Comune: unexpected operator
/usr/local/bin/gencert-public: 46: curl: not found
[E] ORGANIZATION_IDENTIFIER refers to something that does not exists
[I] Check it by yourself at https://indicepa.gov.it/ricerca/n-dettaglioamministrazione.php?cod_amm=c_h501`

**Comment by psmiraglia** [comment]
How the `gencert` scripts are executed? With Docker or directly on the host?

Anyway, your problem now is about `curl`, which is not installed on your system/container.

**Comment by psmiraglia** [comment]
I made a check on the docker image and, according to your error, `curl` is not present by default. Please pull the code from  [issue/13] and try it. Everything should be fine now.

[issue/13]: https://github.com/italia/spid-compliant-certificates/tree/issue/13

**Comment by nicolapippa** [comment]
The command used was like this

`docker run -ti --rm --env-file my.env -v "/tmp/mycert:/output" psmiraglia/spid-compliant-certificates`

I confirm that it now works correctly.

Thanks
