### ISSUE TITLE
Estensione agIDcert

### ISSUE THREAD

**Issue by mauromol** [italia/spid-compliant-certificates#21]
L'avviso 29 versione 3, relativamente alla struttura dei certificati per i Service Provider, specifica che:

>2. Nel campo CertificatePolicies:
>  a.  policyIdentifier — contenente quantomeno uno dei seguenti identificatori:
>    - SP pubblici — spid-publicsector-SP (OID 1.3.76.16.4.2.1);
>    - SP privati — spid-privatesector-SP (OID 1.3.76.16.4.3.1).
>I certificati di sigillo elettronico conformi con la Determinazione AgID No121/2019 s.m.i. 1 – anche se non qualificati –  contengono inoltre l’estensione agIDcert (OID 1.3.76.16 **.6**).

Ora, io non sono affatto un grande esperto di OpenSSL, per questo motivo ho trovato preziosissimo questo vostro esempio per la generazione di certificati conformi a quanto richiesto da AgID (quindi grazie!). Tuttavia, nello script che genera tali certificati vedo questo:
https://github.com/italia/spid-compliant-certificates/blob/9f4becd07ced2de9203fe58c7182bdc45b1a30ad/gencert-public.sh#L109
https://github.com/italia/spid-compliant-certificates/blob/9f4becd07ced2de9203fe58c7182bdc45b1a30ad/gencert-public.sh#L128

Quindi, se capisco bene, lo script sta aggiungendo al certificato la policy che chiamiamo "agid" con OID 1.3.76.16, mentre la specifica richiede la policy chiamata "agIDcert" con OID 1.3.76.16.6.
Da quello che ho capito, il nome non ha importanza, perché "agid" o "agIDcert" è solo un'etichetta che possiamo dare usando un file di etichettatura degli OID sconosciuti. Tuttavia l'OID è effettivamente diverso (manca il ".6" finale, che la specifica segna persino in grassetto!).

Ho provato a controllare se per caso non fosse cambiato qualcosa a riguardo tra le varie versioni dell'avviso 29, ma in realtà vedo che quel requisito è stato aggiunto solo nell'ultima versione (v3) e direttamente con l'OID 1.3.76.16.6 (quindi con il .6 finale).

Si tratta di un refuso?

**Comment by psmiraglia** [comment]
Hi @mauromol thanks for the issue reporting. I would ask @damikael and @peppelinux to investigate about that.

**Comment by damikael** [comment]
Hi, I can confirm what @mauromol said is correct. Certificates must contain OID 1.3.76.16.6  as specified in [Avviso SPID n.29 v.3](https://www.agid.gov.it/sites/default/files/repository_files/spid-avviso-n29v3-specifiche_sp_pubblici_e_privati.pdf)

**Comment by mauromol** [comment]
So, am I correct if I say that the fix is to just change this line:

https://github.com/italia/spid-compliant-certificates/blob/9f4becd07ced2de9203fe58c7182bdc45b1a30ad/gencert-public.sh#L109

to:
```
agid=1.3.76.16.6
```

(as well as the `oids_conf` contents) 
and possibly change the label from "agid" to "agIDcert", which is more in line with what the notice 29v3 says?

Or are there other implications?

**Comment by psmiraglia** [comment]
@mauromol we should change also the values for `explicitText`. Are you interested in creating a PR about that?

**Comment by mauromol** [comment]
@psmiraglia yes, I can create a PR. What `explicitText` should I set though for `agid_notice`? Current one is `cert_SP_Pubblici`.

http://oid-info.com/get/1.3.76.16.6 doesn't suggest too much.
Notice 29v3 references this document: 
[Determinazione AgID n. 121/2019](https://www.agid.gov.it/sites/default/files/repository_files/121_-_dt_dg_n._121_-_17_mag_2019_1.pdf)
and the related attachment:
[Linee guida contenenti le Regole Tecniche e Raccomandazioni afferenti la generazione di certificati elettronici qualificati, firme e sigilli elettronici qualificati e validazioni temporali elettroniche qualificate](https://www.agid.gov.it/sites/default/files/repository_files/regole_e_raccomandazioni_v1.1.pdf)

Perhaps we could use "Conformità alla Determinazione AgID 121/2019" as `explicitText`?
Or a more generic English: "Compliant with AgID recommendations".

I leave the decision to you.

**Comment by psmiraglia** [comment]
Let's start with placeholders that @damikael suggested me some time ago when I started the development of this project

```
1.3.76.16.6 -> agIDcert
1.3.76.16.4.2.1 -> cert_SP_Pub
1.3.76.16.4.3.1 -> cert_SP_Priv
```

**Comment by mauromol** [comment]
Hmmm... let's sum it up to avoid confusion.
I'm speaking about certificates for Public Service Providers:

- AgID required the certificate to have in the field `CertificatePolicies` two `policyIdentifier`s
- the first one has OID=1.3.76.16.4.2.1, its technical name is `spid-publicsector-SP` and it's extended name (human readable text) is currently set to `Service Provider SPID Pubblico`
- the second one has OID=1.3.76.16.6, its technical name is `agIDcert` and it's extended name (human readable text) is the one we have to decide

The fix is that the second policyIdentifier is currently set in this way:
- OID=1.3.76.16 (wrong, the trailing ".6" is missing), technical name = `agid` (while I would say `agIDcert` is more correct) and an extended text of `cert_SP_Pubblici`

Honestly, I don't think `cert_SP_Pubblici` is the right extended name for `agIDcert`: if I understand it correctly, this `agIDcert` policy is a generic one, which states the certificate is compliant to AgID recommendations and is included also in non-Public Service Provider certificates.

This is why I was wondering whether "Compliant with AgID recommendations" or something like that was a better choice for this "extended text".

Regarding the Private Service Providers: I don't know if it's worth to still support them. The AgID notice 29v3 says:

> A seguito dell’accreditamento presso AgID, i SP privati ricevono un certificato di federazione3 emesso
dall’infrastruttura a chiave pubblica (PKI) che AgID ha istituito appositamente per la gestione dell’intera
federazione SPID.

So, this means that private SPs must ask AgID for the certificates, they can't generate them on their own. This is consistent with [notice 23v2](https://www.agid.gov.it/sites/default/files/repository_files/spid-avviso-n23-certificati-agid-per-soggetti-spid_v.2_0.pdf), which also states that the only subjects for which a certificate shall not currently be requested to AgID are Public simple Service Providers.

**Comment by psmiraglia** [comment]
> Hmmm... let's sum it up to avoid confusion.

Where is the fun without confusion? :smile: 

> I'm speaking about certificates for Public Service Providers:
> 
> * AgID required the certificate to have two `policyIdentifier`s in the field `CertificatePolicies`:
> * the first one has OID=1.3.76.16.4.2.1, its technical name is `spid-publicsector-SP` and it's extended name (human readable text) is currently set to `Service Provider SPID Pubblico`

The value `Service Provider SPID Pubblico` was my own initiative. It was before the @damikael suggestion to use `cert_SP_Pub`. In my understanding, this value comes from an internal discussion at AgID that still not produced any public specification.

> * the second one has OID=1.3.76.16.6, its technical name is `agIDcert` and it's extended name (human readable text) is the one we have to decide

Same as above.

> The fix is that the second policyIdentifier is currently set in this way:
> 
> * OID=1.3.76.16 (wrong, the trailing ".6" is missing), technical name = `agid` (while I would say `agIDcert` is more correct) and an extended text of `cert_SP_Pubblici`
> 
> Honestly, I don't think `cert_SP_Pubblici` is the right extended name for `agIDcert`: if I understand it correctly, this `agIDcert` policy is a generic one, which states the certificate is compliant to AgID recommendations and is included also in non-Public Service Provider certificates.

You're right! This is purely a my fault...

> This is why I was wondering whether "Compliant with AgID recommendations" or something like that was a better choice for this "extended text".

As for `1.3.76.16.6` and `1.3.76.16.4.2.1` (and also `1.3.76.16.4.3.1`), rumors say that the `UserNotice.explicitText` will contain just a label (like `cert_SP_Pub`). This is why I suggested you to use

```
1.3.76.16.6 -> agIDcert
1.3.76.16.4.2.1 -> cert_SP_Pub
1.3.76.16.4.3.1 -> cert_SP_Priv
```

> Regarding the Private Service Providers: I don't know if it's worth to still support them. The AgID notice 29v3 says:
> 
> > A seguito dell’accreditamento presso AgID, i SP privati ricevono un certificato di federazione3 emesso
> > dall’infrastruttura a chiave pubblica (PKI) che AgID ha istituito appositamente per la gestione dell’intera
> > federazione SPID.
> 
> So, this means that private SPs must ask AgID for the certificates, they can't generate them on their own. This is consistent with [notice 23v2](https://www.agid.gov.it/sites/default/files/repository_files/spid-avviso-n23-certificati-agid-per-soggetti-spid_v.2_0.pdf), which also states that the only subjects for which a certificate shall not currently be requested to AgID are Public simple Service Providers.

About private sector, the tool (`gencert-private.sh`) can be used to generate only the private key and the CSR (Certificate Signing Request). Despite quite simple, many people think this is a very difficult task.

**Comment by mauromol** [comment]
OK, so I will set the "explicitText" to:

- `agIDcert` for `agIDcert` policy
- `cert_SP_Pub` for `spid-publicsector-SP` policy

I will provide a PR soon.

>About private sector, the tool (gencert-private.sh) can be used to generate only the private key and the CSR (Certificate Signing Request). Despite quite simple, many people think this is a very difficult task.

Fair point. I'll try to look at the `gencert-private.sh` as well.
