### ISSUE TITLE
Repository splitting

### ISSUE THREAD

**Issue by psmiraglia** [italia/spid-compliant-certificates#28]
Commit 6b8f615 introduces, besides the Shell implementation, a Python native version of the tool. What do you think about  splitting the current repository in language specific ones? For instance, we could have

- `italia/shell-spid-compliant-certificates` with the Shell version of the tool
- `italia/python-spid-compliant-certificates` with the Python version of the tool

I would ask you to react with :+1: if you agree on splitting. Otherwise, react with :-1:. Of course, feel free to comment about why we should (or should not) split.

**Comment by leonardfactory** [comment]
I agree, but I'd suggest `spid-compliant-certificates-shell` and `spid-compliant-certificates-python` 😄

**Comment by psmiraglia** [comment]
After a week and no oppositions, I think it's time to split!

I would ask someone with the power (maybe HeMan or @peppelinux) to create the repositories (empty please)

- `italia/spid-compliant-certificates-python`
- `italia/spid-compliant-certificates-shell`

and to make me able to do the dirty job. After the splitting, the current repository will be archived.

**Comment by psmiraglia** [comment]
After a call with @peppelinux, we agreed on...

- Creating a new repository named `spid-compliant-certificates-python` for the Python native implementation.
- Keeping the shell implementation in the current repository without creating a specific repository. All the Python related (e.g. sources, workflows, Dockerfile) will be moved to `spid-compliant-certificates-python`.

**Comment by psmiraglia** [comment]
FYI, https://github.com/italia/spid-compliant-certificates-python
