### ISSUE TITLE
Add Release

### ISSUE THREAD

**Issue by AntonioGiovanniSchiavone** [italia/spid-compliant-certificates#35]
Unlike other projects published on Developers Italia, a published release is missing.

**Comment by peppelinux** [comment]
Hi @AntonioGiovanniSchiavone,
see https://github.com/italia/spid-compliant-certificates/issues/28 and have your say

I think that the first release is strictly linked to that issue

**Comment by AntonioGiovanniSchiavone** [comment]
Done
