### ISSUE TITLE
Controllo esistenza codice amministrazione fallito sul nuovo sito IPA

### ISSUE THREAD

**Issue by nunzionapolitano** [italia/spid-compliant-certificates#42]
Il controllo 
CHECK_URL="https://indicepa.gov.it/ricerca/n-dettaglioamministrazione.php?cod_amm=${IPA_CODE}"
nel file "gencert.public.sh"
non funziona più in quanto nel nuovo sito tale  pagina non è presente.

**Comment by mfortini** [comment]
La nuova risorsa potrebbe essere https://indicepa.gov.it/ipa-dati/dataset/enti/resource/d09adf99-dc10-4349-8c53-27b1e5aa97b6

`https://indicepa.gov.it/ipa-dati/api/3/action/datastore_search_sql?sql=SELECT * from "d09adf99-dc10-4349-8c53-27b1e5aa97b6" WHERE "Codice_IPA" =  'c_h%'`

**Comment by AntonioGiovanniSchiavone** [comment]
Ne abbiamo discusso in [questa issue](https://github.com/italia/spid-compliant-certificates/issues/25).

**Comment by peppelinux** [comment]
Su spid-sp-test sto usando questo
https://github.com/italia/spid-sp-test/blob/main/src/spid_sp_test/indicepa.py così:

````
from spid_sp_test import indicepa
get_indicepa_by_ipacode('unical')
indicepa.get_indicepa_by_ipacode('unical')
````

@psmiraglia se questo approccio ti convince potremmo aggiornare l'attuale procedura, che ne pensi?

**Comment by peppelinux** [comment]
Unito
https://github.com/italia/spid-compliant-certificates/pull/43
